0 lines (195 sloc)  6.64 KB
  
name: Minecraft PC Data Dumper

on:
  workflow_dispatch:
    inputs:
      minecraft-version:
        description: 'Version of minecraft to dump data from'
        default: '1.16.5'
        required: true

jobs:
    use-tool:
      - name: checkout
        run: actions/checkout@v2
      - name: run tool
        run: node image_names.js ${{ github.event.inputs.minecraft-version }} out temp
      - name: upload to artifact
        uses: actions/upload-artifact@v2
        with:
          name: data
          path: out/${{ github.event.inputs.minecraft-version }}
    make-pr:
      needs: use-tool
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_PASSWORD }}
          repository: PrismarineJS/minecraft-assets
      - name: download from artifact
        uses: actions/download-artifact@v2.0.9
        with:
          name: data
          path: data/${{ github.event.inputs.minecraft-version }}/
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
            commit-message: Add data from ${{ github.event.inputs.minecraft-version }}
            title: Add data from ${{ github.event.inputs.minecraft-version }}
            body: |
              Auto-generated by a GH workflow
            branch: add-${{ github.event.inputs.minecraft-version }}-images
            token: ${{ secrets.PAT_PASSWORD }}
